plugins {
    id 'application'
	id 'java'
	id 'java-library'
	id 'eclipse'
    id 'maven-publish'
}

application {
    applicationDefaultJvmArgs = ['-Dgreeting.language=en']
    mainClass = 'org.hl7.fhir.AHRQProfiler'
}

group = 'org.hl7.fhir'
version = '0.0.1' // Set project-level property
def applicationName = 'fhir.ig' // Local variable for the artifact name


java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
	mavenLocal()
    mavenCentral()
    flatDir {
	    dirs 'libs'
    }
}

sourceSets {
    main {
        java {
            srcDirs 'src/main/java'
            srcDirs 'src/main/resources'
           }
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.slf4j:slf4j-api:2.0.0'
    }
}

dependencies {
	implementation libs.args4j
	implementation libs.fhirEmf
	implementation libs.emfjson
    implementation libs.emfCommon
    implementation libs.emfEcore
    implementation libs.emfEcoreXMI
    implementation libs.jacksonAnnotations
    implementation libs.jacksonDatabind
   
   	// Logging
	implementation libs.slf4jAPI
	implementation libs.logbackClassic
    
    testImplementation libs.junitJupiter
    testImplementation libs.junitJupiterAPI
    testImplementation libs.emfEcoreXMI
    
    testImplementation 'org.everit.json:org.everit.json.schema:1.5.0'
    testImplementation 'com.networknt:json-schema-validator:1.0.42'
}

jar {
    manifest {
        attributes 'Main-Class': provider { application.mainClass.get() }
    }
    
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE  // Ignore duplicate entries

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    exclude("META-INF/*.RSA", "META-INF/*.DSA", "META-INF/*.SF", "META-INF/MANIFEST.MF")
}

processResources {
  from ('src/main/java') {
     include '**/*.ecore'
  }
}
 
test {
    useJUnitPlatform()
    testLogging.showStandardStreams = true
}

task checkSignedJars {
    doLast {
        println "Scanning for signed JARs..."
        configurations.runtimeClasspath.files.each { jarFile ->
            if (jarFile.name.endsWith(".jar")) {
                println "Checking: ${jarFile.name}"
                def hasSignature = false
                zipTree(jarFile).visit { file ->
                    if (file.name.matches("META-INF/.*\\.(SF|RSA|DSA|EC)")) {
                        println "Found signed JAR: ${jarFile.name} (Signature File: ${file.name})"
                        hasSignature = true
                    }
                }
                if (!hasSignature) {
                    println "No signature found in: ${jarFile.name}"
                }
            }
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId applicationName
            version project.version
            from(components.java)
        }
	}
}
